influxdata/influxdb-client-java

- client/src/main/java/org/influxdata/client/AuthorizationsApi.java
- client/src/main/java/org/influxdata/client/BucketsApi.java
- client/src/main/java/org/influxdata/client/LabelsApi.java
- client/src/main/java/org/influxdata/client/OrganizationsApi.java
- client/src/main/java/org/influxdata/client/ScraperTargetsApi.java
- client/src/main/java/org/influxdata/client/SourcesApi.java
- client/src/main/java/org/influxdata/client/TasksApi.java
- client/src/main/java/org/influxdata/client/UsersApi.java
- client/src/main/java/org/influxdata/client/domain/Authorization.java
- client/src/main/java/org/influxdata/client/internal/AuthorizationsApiImpl.java
- client/src/main/java/org/influxdata/client/internal/BucketsApiImpl.java
- client/src/main/java/org/influxdata/client/internal/LabelsApiImpl.java
- client/src/main/java/org/influxdata/client/internal/OrganizationsApiImpl.java
- client/src/main/java/org/influxdata/client/internal/ScraperTargetsApiImpl.java
- client/src/main/java/org/influxdata/client/internal/SourcesApiImpl.java
- client/src/main/java/org/influxdata/client/internal/TasksApiImpl.java
- client/src/main/java/org/influxdata/client/internal/UsersApiImpl.java
- client/src/test/java/org/influxdata/client/ITAuthorizationsApiTest.java
- client/src/test/java/org/influxdata/client/ITBucketsApiTest.java
- client/src/test/java/org/influxdata/client/ITLabelsApiTest.java
- client/src/test/java/org/influxdata/client/ITOrganizationsApiTest.java
- client/src/test/java/org/influxdata/client/ITScraperTargetsApiTest.java
- client/src/test/java/org/influxdata/client/ITSourcesApi.java
- client/src/test/java/org/influxdata/client/ITTasksApiTest.java
- client/src/test/java/org/influxdata/client/ITUsersApiTest.java
> Added possibility to clone management entities

- client/README.md
- client/src/main/java/org/influxdata/client/InfluxDBClient.java
- client/src/main/java/org/influxdata/client/TelegrafsApi.java
- client/src/main/java/org/influxdata/client/domain/AbstractHasLabels.java
- client/src/main/java/org/influxdata/client/domain/Task.java
- client/src/main/java/org/influxdata/client/domain/TelegrafAgent.java
- client/src/main/java/org/influxdata/client/domain/TelegrafConfig.java
- client/src/main/java/org/influxdata/client/domain/TelegrafConfigs.java
- client/src/main/java/org/influxdata/client/domain/TelegrafPlugin.java
- client/src/main/java/org/influxdata/client/domain/TelegrafPluginType.java
- client/src/main/java/org/influxdata/client/internal/InfluxDBClientImpl.java
- client/src/main/java/org/influxdata/client/internal/InfluxDBService.java
- client/src/main/java/org/influxdata/client/internal/TelegrafsApiImpl.java
- client/src/test/java/org/influxdata/client/ITTasksApiTest.java
- client/src/test/java/org/influxdata/client/ITTelegrafsApi.java
- client/src/test/java/org/influxdata/client/ITWriteQueryApiTest.java
- scripts/influxdb-restart.sh
> Implemented "/api/v2/telegrafs" HTTP API endpoint

- client-core/src/main/java/org/influxdata/exceptions/RequestEntityTooLargeException.java
- client-core/src/main/java/org/influxdata/internal/AbstractRestClient.java
- client-core/src/test/java/org/influxdata/internal/RestClientTest.java
- client-reactive/README.md
- client-reactive/src/main/java/org/influxdata/client/reactive/WriteReactiveApi.java
- client-reactive/src/main/java/org/influxdata/client/reactive/internal/InfluxDBReactiveService.java
- client-reactive/src/main/java/org/influxdata/client/reactive/internal/WriteReactiveApiImpl.java
- client-test/src/main/java/org/influxdata/test/AbstractMockServerTest.java
- client/README.md
- client/src/main/java/org/influxdata/client/InfluxDBClient.java
- client/src/main/java/org/influxdata/client/WriteApi.java
- client/src/main/java/org/influxdata/client/WriteOptions.java
- client/src/main/java/org/influxdata/client/internal/AbstractWriteClient.java
- client/src/main/java/org/influxdata/client/internal/InfluxDBService.java
- client/src/main/java/org/influxdata/client/internal/WriteApiImpl.java
- client/src/main/java/org/influxdata/client/write/events/WriteRetriableErrorEvent.java
- client/src/test/java/org/influxdata/client/ITWriteQueryApiTest.java
- client/src/test/java/org/influxdata/client/WriteApiTest.java
- client/src/test/java/org/influxdata/client/WriteEventListener.java
> Added writes retry strategy

- .travis.yml
- CHANGELOG.md
> #37: Switch CI from oraclejdk to openjdk

- CHANGELOG.md
- client-reactive/src/main/java/org/influxdata/client/reactive/internal/InfluxDBClientReactiveImpl.java
- client-reactive/src/main/java/org/influxdata/client/reactive/internal/WriteReactiveApiImpl.java
- client/README.md
- client/src/main/java/org/influxdata/client/InfluxDBClientOptions.java
- client/src/main/java/org/influxdata/client/WriteOptions.java
- client/src/main/java/org/influxdata/client/internal/AbstractWriteClient.java
- client/src/main/java/org/influxdata/client/internal/WriteApiImpl.java
- client/src/main/java/org/influxdata/client/write/Point.java
- client/src/main/java/org/influxdata/client/write/PointSettings.java
- client/src/test/java/org/influxdata/client/ITWriteQueryApi.java
- client/src/test/java/org/influxdata/client/InfluxDBClientFactoryTest.java
- client/src/test/java/org/influxdata/client/write/PointSettingsTest.java
- client/src/test/java/org/influxdata/client/write/PointTest.java
- client/src/test/resources/influx2.properties
> Default tags

- CHANGELOG.md
- client-kotlin/src/main/kotlin/com/influxdb/client/kotlin/QueryKotlinApi.kt
- client-kotlin/src/main/kotlin/com/influxdb/client/kotlin/internal/QueryKotlinApiImpl.kt
- client-reactive/src/main/java/com/influxdb/client/reactive/QueryReactiveApi.java
- client-reactive/src/main/java/com/influxdb/client/reactive/internal/QueryReactiveApiImpl.java
- client-scala/src/main/scala/com/influxdb/client/scala/QueryScalaApi.scala
- client-scala/src/main/scala/com/influxdb/client/scala/internal/QueryScalaApiImpl.scala
- client/README.md
- client/src/generated/java/com/influxdb/client/domain/CheckViewProperties.java
- client/src/generated/java/com/influxdb/client/domain/NotificationEndpointBase.java
- client/src/generated/java/com/influxdb/client/domain/Task.java
- client/src/generated/java/com/influxdb/client/domain/TaskCreateRequest.java
- client/src/generated/java/com/influxdb/client/service/QueryService.java
- client/src/generated/java/com/influxdb/client/service/WriteService.java
- client/src/main/java/com/influxdb/client/QueryApi.java
- client/src/main/java/com/influxdb/client/internal/AbstractWriteClient.java
- client/src/main/java/com/influxdb/client/internal/QueryApiImpl.java
- client/src/main/java/com/influxdb/client/internal/WriteApiBlockingImpl.java
- client/src/main/resources/swagger.yml
- client/src/test/java/com/influxdb/client/ITWriteQueryApi.java
- client/src/test/java/com/influxdb/client/QueryApiTest.java
> Org id name interchangeably

- CHANGELOG.md
- client-kotlin/README.md
- client-reactive/README.md
- client-scala/README.md
- client/README.md
- client/src/main/java/com/influxdb/client/internal/GzipInterceptor.java
- client/src/test/java/com/influxdb/client/ITWriteQueryApi.java
- client/src/test/java/com/influxdb/client/internal/GzipInterceptorTest.java
> #50: Added support for gzip compression of query response

- .circleci/config.yml
- client-reactive/src/test/java/com/influxdb/client/reactive/ITWriteQueryReactiveApi.java
- client/src/test/java/com/influxdb/client/ITInfluxDBClient.java
- scripts/influxdb-restart.sh
Configured CircleCI to build java client: https://circleci.com/gh/influxdata/workflows/influxdb-client-java
> Configuring CircleCI

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/write/Point.java
- client/src/test/java/com/influxdb/client/ITBucketsApi.java
- client/src/test/java/com/influxdb/client/write/PointTest.java
> Skip NaN and infinity values

- client-legacy/src/test/java/com/influxdb/client/flux/ITFluxClient.java
- scripts/influxdb-restart.sh
Use wget to check if services are started
> Fix CI builds

- CHANGELOG.md
- README.md
- client-kotlin/README.md
- client-legacy/README.md
- client-reactive/README.md
- client-scala/README.md
- client/README.md
- client/src/main/java/com/influxdb/client/internal/AbstractWriteClient.java
- client/src/test/java/com/influxdb/client/WriteApiTest.java
- spring/README.md
The serialization to line protocol optimized by StringBuilder.
> #60: The Writes performance optimized

- client/src/main/java/com/influxdb/client/write/PointSettings.java
> fix: android compatibility (#69)

- README.md
- client/README.md
- examples/src/main/java/example/InfluxDB2Example.java
- examples/src/main/java/example/PlatformExample.java
- examples/src/main/java/example/WriteDataBlocking.java
- examples/src/main/java/example/WriteDataPoint.java
> doc: fixed precision in examples

- flux-dsl/README.md
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/restriction/ColumnRestriction.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/FilterFluxTest.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/restriction/RestrictionsTest.java
> fix: #75 added exists operator support

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/write/Point.java
- client/src/test/java/com/influxdb/client/internal/MeasurementMapperTest.java
- client/src/test/java/com/influxdb/client/write/PointTest.java
> feat: Time field in Point supports BigInteger and BigDecimal

- CHANGELOG.md
- flux-dsl/README.md
- flux-dsl/src/main/java/com/influxdb/query/dsl/Flux.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/ReduceFlux.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/ReduceFluxTest.java
> feat: Add reduce operator to FluxDSL

- CHANGELOG.md
- client-core/src/main/java/com/influxdb/internal/UserAgentInterceptor.java
- client-core/src/test/java/com/influxdb/internal/ITUserAgentInterceptor.java
- client-legacy/src/main/java/com/influxdb/client/flux/internal/FluxApiImpl.java
- client/src/main/java/com/influxdb/client/internal/AbstractInfluxDBClient.java
- client/src/test/java/com/influxdb/client/WriteApiTest.java
- pom.xml
> feat: add User-Agent request header

- CHANGELOG.md
- client-core/src/main/java/com/influxdb/query/internal/FluxResultMapper.java
- client-core/src/test/java/com/influxdb/query/internal/FluxResultMapperTest.java
> feat: @Column supports super class inheritance

- client/src/test/java/com/influxdb/client/ITBucketsApi.java
- client/src/test/java/com/influxdb/client/ITSourcesApi.java
- client/src/test/java/com/influxdb/client/ITTemplatesApi.java
> fix: cannot find buckets after delete an organization

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/write/Point.java
- client/src/test/java/com/influxdb/client/ITAuthorizationsApi.java
- client/src/test/java/com/influxdb/client/ITChecksApi.java
- client/src/test/java/com/influxdb/client/ITDashboardsApi.java
- client/src/test/java/com/influxdb/client/ITNotificationEndpointsApi.java
- client/src/test/java/com/influxdb/client/ITNotificationRulesApi.java
- client/src/test/java/com/influxdb/client/ITQueryService.java
- client/src/test/java/com/influxdb/client/ITTasksApi.java
- client/src/test/java/com/influxdb/client/ITTelegrafsApi.java
- client/src/test/java/com/influxdb/client/ITVariablesApi.java
- client/src/test/java/com/influxdb/client/write/PointTest.java
> feat: Add addTags and addFields helper functions to Point object

- CHANGELOG.md
- README.md
- client/src/main/java/com/influxdb/client/InfluxDBClientFactory.java
- client/src/test/java/com/influxdb/client/InfluxDBClientFactoryTest.java
- examples/src/main/java/example/InfluxDB18Example.java
> docs: Clarify how to use a client with InfluxDB 1.8

- client-core/src/main/java/com/influxdb/internal/UserAgentInterceptor.java
> Fixes #104 - Added nullity check after call to getPackage

- CHANGELOG.md
- client-core/src/main/java/com/influxdb/Arguments.java
- client-core/src/test/java/com/influxdb/ArgumentsDurationTest.java
Closes #110 
Added support "inf" in Duration
> feat: Added support "inf" in Duration

- README.md
> Set version to 1.8.0 in dependencies

- .circleci/config.yml
- client-legacy/src/test/java/com/influxdb/client/flux/AbstractITFluxClient.java
- client-legacy/src/test/java/com/influxdb/client/flux/ITFluxClient.java
- client/src/test/java/com/influxdb/client/AbstractITClientTest.java
- scripts/influxdb-onboarding.sh
Using CircleCI Docker to build client instead dedicated VM.
> chore: switch to build by Docker instead dedicated VM

- CHANGELOG.md
- client-core/pom.xml
- client-core/src/main/java/com/influxdb/exceptions/InfluxException.java
- client-core/src/main/java/com/influxdb/internal/AbstractQueryApi.java
- client-core/src/test/java/com/influxdb/exceptions/InfluxExceptionTest.java
- client-core/src/test/java/com/influxdb/internal/QueryAbstractApiTest.java
- client-kotlin/pom.xml
- client-legacy/pom.xml
- client-legacy/src/main/java/com/influxdb/client/flux/internal/FluxApiImpl.java
- client-reactive/pom.xml
- client-scala/pom.xml
- client-test/pom.xml
- client/pom.xml
- client/src/test/java/com/influxdb/client/ITMonitoringAlerting.java
- client/src/test/java/com/influxdb/client/WriteApiTest.java
- examples/pom.xml
- flux-dsl/pom.xml
- pom.xml
- spring/pom.xml
Closes #196
Remove badly licenced org.json library and relace it with gson.
> fix: Remove org.json dependency

- client/src/test/java/com/influxdb/client/ITWriteQueryApi.java
https://app.circleci.com/pipelines/github/influxdata/influxdb-client-java/863/workflows/8c21ce26-9e72-472e-9a1d-93fb5dd97bf0/jobs/2651
> chore: fixed flaky test

- CHANGELOG.md
- spring/pom.xml
The Spring configuration processor generates metadata that helps the IDE autocompletes in the `application.properties`.
> feat: add spring configuration processor (ready for review/merge)

- README.md
- client-kotlin/README.md
- client-legacy/README.md
- client-reactive/README.md
- client-scala/README.md
Added unified documentation section.
> docs: add client docs links

- CHANGELOG.md
- client/README.md
- client/src/test/java/com/influxdb/client/InfluxDBClientTest.java
Added docs how to configure proxy.
> docs: how to configure proxy

- CHANGELOG.md
- client-kotlin/src/main/kotlin/com/influxdb/client/kotlin/QueryKotlinApi.kt
- client-reactive/src/main/java/com/influxdb/client/reactive/QueryReactiveApi.java
- client-reactive/src/main/java/com/influxdb/client/reactive/internal/QueryReactiveApiImpl.java
- client-reactive/src/test/java/com/influxdb/client/reactive/ITWriteQueryReactiveApi.java
- client-scala/src/main/scala/com/influxdb/client/scala/QueryScalaApi.scala
- client/README.md
- client/src/main/java/com/influxdb/client/QueryApi.java
- client/src/main/java/com/influxdb/client/internal/QueryApiImpl.java
- client/src/test/java/com/influxdb/client/ITWriteQueryApi.java
- client/src/test/java/com/influxdb/client/QueryApiTest.java
- examples/README.md
- examples/src/main/java/example/ParameterizedQuery.java
This PR implements support for Parameterized Queries for InfluxDB Cloud. 
https://docs.influxdata.com/influxdb/cloud/query-data/parameterized-queries
> feat: parameterized queries support

- pom.xml
Remove Bonitoo Snapshot repository from `pom.xml`.
> chore: remove Bonitoo Snapshot repository

- client-kotlin/README.md
- client-legacy/README.md
- client-reactive/README.md
- client-scala/README.md
- client/README.md
- spring/README.md
Related to https://github.com/influxdata/influxdb-client-java/pull/306
Fixed rest of READMEs. For more info see #306.
> fix: installation instruction for Gradle

- .circleci/config.yml
- client/pom.xml
- client/src/test/java/com/influxdb/client/ITBenchmarkTest.java
- client/src/test/java/com/influxdb/client/benchmark/BenchmarkOptions.java
- client/src/test/java/com/influxdb/client/benchmark/ClientBenchmark.java
- pom.xml
This PR adds client benchmarking test that validates the client writes in multithreaded load.
> test: add client performance/benchmark test

- client/src/test/java/com/influxdb/client/ITQueryService.java
Fix tests to be compatible with InfluxDB 2.2.
> fix(test): reflect changes in InfluxDB 2.2

- flux-dsl/README.md
Closes #349
Added description how to use named properties.
> docs(flux): how to use named properties

- CHANGELOG.md
- client-core/pom.xml
- client-kotlin/pom.xml
- client-legacy/pom.xml
- client-osgi/pom.xml
- client-reactive/pom.xml
- client-scala/cross/2.12/pom.xml
- client-scala/cross/2.13/pom.xml
- client-test/pom.xml
- client-utils/pom.xml
- client/pom.xml
- examples/pom.xml
- flux-dsl/pom.xml
- karaf/karaf-assembly/pom.xml
- karaf/karaf-features/pom.xml
- karaf/karaf-kar/pom.xml
- karaf/pom.xml
- pom.xml
- spring/pom.xml
Change upcoming version to `6.2.0`.
> chore(deploy): upcoming version is 6.2.0

- CHANGELOG.md
- flux-dsl/README.md
- flux-dsl/src/main/java/com/influxdb/query/dsl/Flux.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/FillFlux.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/FillFluxTest.java
> feat: add fill flux

- client/src/generated/java/com/influxdb/client/service/InfluxQLQueryService.java
The `InfluxQLQueryService` is generated by `apigen`. For more info see linked PR.
> refactor: InfluxQLQueryService is generated by apigen

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/write/Point.java
- client/src/test/java/com/influxdb/client/write/PointTest.java
Closes #411
The `Point#time` is public.
> feat: add possibility to get time from `Point`

- client-scala/cross/2.12/pom.xml
- client-scala/cross/2.13/pom.xml
- pom.xml
Specify the `akka` version at one place.
> chore(deps): specify akka version at one place

- client-scala/src/main/scala/com/influxdb/client/scala/internal/WriteScalaApiImpl.scala
- client-scala/src/test/scala/com/influxdb/client/scala/WriteScalaApiTest.scala
The current Akka Streams API requires to materialize a different stream whenever we want to write a point. Sources like Kafka never end, and thus the current API requires to materialize a different stream for each point, where a single stream would do:
```scala
val source: Source[Point, NotUsed] = fromKafka() // we get a stream that never ends
source.mapAsync(parallelism) { point =>
Source.single(point).runWith(writeApi.writePoint)
}.runWith(Sink.foreach(_ => println("recoded point")
```
With these changes we can do:
```scala
val source: Source[Point, NotUsed] = fromKafka() // we get a stream that never ends
source.runWith(writeApi.writePoint)
```
My apologies if this PR is not following the desired approach. As an avid Akka Streams users, I think …
> feat: Ingest Points continuously with Akka Stream

- .circleci/config.yml
- CHANGELOG.md
> chore: add JDK 19 to CI pipeline

- client-kotlin/README.md
- client-legacy/README.md
- client-reactive/README.md
- client-scala/README.md
- client/README.md
- flux-dsl/README.md
- karaf/karaf-assembly/pom.xml
- karaf/karaf-features/pom.xml
- karaf/karaf-kar/pom.xml
- spring/README.md
Use correct version of the client in READMEs.
> docs: actual version of the client is 6.8.0

- spring/pom.xml
- spring/src/test/java/com/influxdb/spring/influx/InfluxDB2AutoConfigurationTest.java
* Remove spring-test dependency
* Remove usage of ReflectionTestUtils
* Use assertj's extracting
> chore: improve tests

- pom.xml
For more info see: https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#plugins-tested-for-compatibility
> chore(nexus): add nexus-staging-maven-plugin for auto staging deployed artifacts
