influxdata/influxdb-client-java

- CHANGELOG.md
- README.md
- client-reactive/README.md
- client-reactive/src/main/java/org/influxdata/client/reactive/internal/WriteReactiveApiImpl.java
- client/README.md
- client/src/main/java/org/influxdata/client/InfluxDBClient.java
- client/src/main/java/org/influxdata/client/WriteApi.java
- client/src/main/java/org/influxdata/client/WriteApiBlocking.java
- client/src/main/java/org/influxdata/client/internal/AbstractWriteClient.java
- client/src/main/java/org/influxdata/client/internal/InfluxDBClientImpl.java
- client/src/main/java/org/influxdata/client/internal/WriteApiBlockingImpl.java
- client/src/test/java/org/influxdata/client/H2OFeetMeasurement.java
- client/src/test/java/org/influxdata/client/ITWriteApiBlocking.java
- client/src/test/java/org/influxdata/client/InfluxDBClientTest.java
Closes #41 #7 
Added synchronous blocking API to Write time-series data into InfluxDB 2.0
> Added synchronous blocking API to Write time-series data into InfluxDB 2.0

- CHANGELOG.md
- client/src/main/java/org/influxdata/client/internal/AbstractWriteClient.java
- client/src/main/java/org/influxdata/client/write/Point.java
- client/src/test/java/org/influxdata/client/ITWriteApiBlocking.java
- client/src/test/java/org/influxdata/client/ITWriteQueryApi.java
- client/src/test/java/org/influxdata/client/write/PointTest.java
> #43: The data point without field should be ignored

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/internal/LabelsApiImpl.java
- client/src/test/java/com/influxdb/client/ITLabelsApi.java
> LabelsApi: orgID parameter has to be pass as second argument

- CHANGELOG.md
- client-kotlin/src/main/kotlin/com/influxdb/client/kotlin/InfluxDBClientKotlin.kt
- client-kotlin/src/test/kotlin/com/influxdb/client/kotlin/InfluxDBClientKotlinFactoryTest.kt
- client-reactive/src/main/java/com/influxdb/client/reactive/InfluxDBClientReactive.java
- client-reactive/src/test/java/com/influxdb/client/reactive/InfluxDBClientReactiveFactoryTest.java
- client/src/main/java/com/influxdb/client/InfluxDBClient.java
- client/src/test/java/com/influxdb/client/InfluxDBClientTest.java
Use Try-With-Resources without catching clause:
```java
try (InfluxDBClient client = InfluxDBClientFactory.create(mockServer.url("/").url().toString())){
...
}
```
instead
```
try (InfluxDBClient client = InfluxDBClientFactory.create(mockServer.url("/").url().toString())){
...
} catch (Exception e) {
...            
}
```
> #61: Use Try-With-Resources without catching clause

- CHANGELOG.md
- client-kotlin/src/test/kotlin/com/influxdb/client/kotlin/ITQueryKotlinApi.kt
- client-reactive/README.md
- client-reactive/src/main/java/com/influxdb/client/reactive/internal/InfluxDBClientReactiveImpl.java
- client-reactive/src/main/java/com/influxdb/client/reactive/internal/WriteReactiveApiImpl.java
- client-scala/src/test/scala/com/influxdb/client/scala/ITQueryScalaApiQuery.scala
- client/src/main/java/com/influxdb/client/internal/AbstractInfluxDBClient.java
- client/src/main/java/com/influxdb/client/internal/AbstractWriteClient.java
- client/src/main/java/com/influxdb/client/internal/InfluxDBClientImpl.java
- client/src/main/java/com/influxdb/client/internal/WriteApiImpl.java
- client/src/test/java/com/influxdb/client/ITWriteApiBlocking.java
- client/src/test/java/com/influxdb/client/ITWriteQueryApi.java
- client/src/test/java/com/influxdb/client/WriteApiTest.java
- examples/src/main/java/example/InfluxDB2ReactiveExampleWriteEveryTenSeconds.java
Closes #78
Closes #33
Calling `InfluxDBClient.close` should also close a created `writeApi`:
```java
InfluxDBClient influxDBClient = InfluxDBClientFactory.create(influxdbConfig.getAddress(), influxdbConfig.getToken().toCharArray());
WriteApi writeApi = influxDBClient.getWriteApi();
writeApi.writeRecord("b1", "org1", WritePrecision.NS,"h2o_feet water_level=1.0 1")
writeApi.close();
influxDBClient.close();
```
> fix: InfluxDBClient.close also dispose a created writeApi

- CHANGELOG.md
- client-core/src/main/java/com/influxdb/query/internal/FluxCsvParser.java
- client-core/src/test/java/com/influxdb/query/internal/FluxCsvParserTest.java
- client-core/src/test/java/com/influxdb/query/internal/FluxStructureSerializationTest.java
- client/src/test/java/com/influxdb/client/ITTasksApi.java
> fix: Correctly parse CSV where multiple results include multiple tables

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/internal/MeasurementMapper.java
- client/src/test/java/com/influxdb/client/WriteApiTest.java
> fix: @Column supports super class inheritance for write measurements

- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/WindowFlux.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/WindowFluxTest.java
Closes #
I'm not sure if I miss anything. I was trying to put "offset" into the function but only found "start". However, according to the spec, "start" does not seem to be an acceptable argument, according to https://github.com/influxdata/flux/blob/master/execute/window.go
> fix bug caused by typo in "WindowFlux"

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/internal/AbstractWriteClient.java
> feat: The closing message of the `WriteApi` has `Fine` log level

- CHANGELOG.md
- client-core/src/main/java/com/influxdb/internal/UserAgentInterceptor.java
- client-core/src/test/java/com/influxdb/internal/ITUserAgentInterceptor.java
- client-kotlin/src/main/kotlin/com/influxdb/client/kotlin/internal/InfluxDBClientKotlinImpl.kt
- client-kotlin/src/test/kotlin/com/influxdb/client/kotlin/InfluxDBClientKotlinTest.kt
- client-legacy/src/main/java/com/influxdb/client/flux/internal/FluxApiImpl.java
- client-reactive/src/main/java/com/influxdb/client/reactive/internal/InfluxDBClientReactiveImpl.java
- client-scala/src/main/scala/com/influxdb/client/scala/internal/InfluxDBClientScalaImpl.scala
- client-scala/src/test/scala/com/influxdb/client/scala/ITInfluxDBClientScala.scala
- client-scala/src/test/scala/com/influxdb/client/scala/ITQueryScalaApiQuery.scala
- client-scala/src/test/scala/com/influxdb/client/scala/InfluxDBClientScalaFactoryTest.scala
- client-scala/src/test/scala/com/influxdb/client/scala/InfluxDBClientScalaTest.scala
- client-test/src/main/java/com/influxdb/test/AbstractMockServerTest.java
- client/src/main/java/com/influxdb/client/internal/AbstractInfluxDBClient.java
- client/src/main/java/com/influxdb/client/internal/InfluxDBClientImpl.java
- client/src/test/java/com/influxdb/client/ITBucketsApi.java
- client/src/test/java/com/influxdb/client/ITChecksApi.java
- client/src/test/java/com/influxdb/client/ITDashboardsApi.java
- client/src/test/java/com/influxdb/client/ITNotificationEndpointsApi.java
- client/src/test/java/com/influxdb/client/ITNotificationRulesApi.java
- client/src/test/java/com/influxdb/client/ITQueryService.java
- client/src/test/java/com/influxdb/client/ITTelegrafsApi.java
- client/src/test/java/com/influxdb/client/ITUsersApi.java
- client/src/test/java/com/influxdb/client/ITVariablesApi.java
- client/src/test/java/com/influxdb/client/QueryApiTest.java
- client/src/test/java/com/influxdb/client/WriteApiTest.java
> feat: scala and kotlin clients has their own user agent string

- README.md
this example  : temperature.time = Instant.now(); is MilliSeconds , so  use WritePrecision.MS.
Closes #
> Instant.now() return is MilliSeconds

- CHANGELOG.md
- client-kotlin/pom.xml
- client-scala/pom.xml
- examples/pom.xml
- pom.xml
- scripts/maven-version-rules.xml
- spring/pom.xml
Update dependencies: 
* akka: 2.6.6
* commons-io: 2.7
* spring: 5.2.7.RELEASE
* retrofit: 2.9.0
* okhttp3: 4.7.2
Update plugins: 
* maven-project-info-reports-plugin: 3.1.0
* dokka-maven-plugin: 0.10.1
* scoverage-maven-plugin: 1.4.1
> feat: update dependencies & plugins

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/write/Point.java
- client/src/test/java/com/influxdb/client/internal/MeasurementMapperTest.java
- client/src/test/java/com/influxdb/client/write/PointTest.java
Closes #127 
* serialization of `\n`, `\r` and `\t` to Line Protocol
* `=` is valid sign for measurement name
> fix: serialization of `\n`, `\r` and `\t` to Line Protocol, `=` is valid sign for measurement name 

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/write/Point.java
- client/src/test/java/com/influxdb/client/write/PointTest.java
Related-to #135
The `measurement name` has to be specified.
> fix: Data Point: measurement name is requiring in constructor

- CHANGELOG.md
- client-legacy/src/main/java/com/influxdb/client/flux/FluxClient.java
- client-reactive/src/main/java/com/influxdb/client/reactive/QueryReactiveApi.java
- client-reactive/src/main/java/com/influxdb/client/reactive/WriteReactiveApi.java
- client/src/main/java/com/influxdb/client/AuthorizationsApi.java
- client/src/main/java/com/influxdb/client/BucketsApi.java
- client/src/main/java/com/influxdb/client/ChecksApi.java
- client/src/main/java/com/influxdb/client/DashboardsApi.java
- client/src/main/java/com/influxdb/client/DeleteApi.java
- client/src/main/java/com/influxdb/client/InfluxDBClient.java
- client/src/main/java/com/influxdb/client/LabelsApi.java
- client/src/main/java/com/influxdb/client/NotificationEndpointsApi.java
- client/src/main/java/com/influxdb/client/NotificationRulesApi.java
- client/src/main/java/com/influxdb/client/OrganizationsApi.java
- client/src/main/java/com/influxdb/client/QueryApi.java
- client/src/main/java/com/influxdb/client/ScraperTargetsApi.java
- client/src/main/java/com/influxdb/client/SourcesApi.java
- client/src/main/java/com/influxdb/client/TasksApi.java
- client/src/main/java/com/influxdb/client/TelegrafsApi.java
- client/src/main/java/com/influxdb/client/TemplatesApi.java
- client/src/main/java/com/influxdb/client/UsersApi.java
- client/src/main/java/com/influxdb/client/VariablesApi.java
- client/src/main/java/com/influxdb/client/WriteApi.java
- client/src/main/java/com/influxdb/client/WriteApiBlocking.java
Closes #137
The APIs are marked as ``@ThreadSafe``.
> feat: marked Apis as @ThreadSafe

- CHANGELOG.md
- client/src/generated/java/com/influxdb/client/JSON.java
- client/src/test/java/com/influxdb/client/OffsetDateTimeTypeAdapterTest.java
- openapi-generator/src/main/resources/Java/libraries/retrofit2/JSON.mustache
Closes #128
Validate OffsetDateTime to satisfy RFC 3339.
> feat: validate OffsetDateTime to satisfy RFC 3339

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/internal/MeasurementMapper.java
Put columns into cache after full initialization.
see - https://github.com/influxdata/influxdb-java/pull/685
> fix: put columns into cache after full initialization

- CHANGELOG.md
- flux-dsl/README.md
- flux-dsl/src/main/java/com/influxdb/query/dsl/Flux.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/CountFlux.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/FirstFlux.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/LastFlux.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/LimitFlux.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/MaxFlux.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/MeanFlux.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/MinFlux.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/SkewFlux.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/SpreadFlux.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/StddevFlux.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/SumFlux.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/CountFluxTest.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/FirstFluxTest.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/LastFluxTest.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/LimitFluxTest.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/MaxFluxTest.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/MeanFluxTest.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/MinFluxTest.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/SkewFluxTest.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/SpreadFluxTest.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/StddevFluxTest.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/SumFluxTest.java
Closes #149
- aggregates now accept only a 'column' parameter https://github.com/influxdata/flux/pull/1142
- add offset parameter to limit operator
> feat: update flux-dsl

- CHANGELOG.md
- client-core/src/test/java/com/influxdb/internal/ITUserAgentInterceptor.java
- client-test/src/main/java/com/influxdb/test/AbstractTest.java
- client/src/main/java/com/influxdb/client/internal/AuthenticateInterceptor.java
- client/src/test/java/com/influxdb/client/internal/AuthenticateInterceptorTest.java
- client/src/test/java/com/influxdb/client/internal/GzipInterceptorTest.java
Closes #146 
The pure OkHttp3 response (not Retrofit) should be always closed.
> fix: always close pure OkHttp3 response

- CHANGELOG.md
- client/README.md
- client/src/main/java/com/influxdb/client/WriteOptions.java
- client/src/main/java/com/influxdb/client/internal/AbstractInfluxDBClient.java
- client/src/main/java/com/influxdb/client/internal/AbstractWriteClient.java
- client/src/main/java/com/influxdb/client/internal/RetryAttempt.java
- client/src/test/java/com/influxdb/client/WriteApiTest.java
- client/src/test/java/com/influxdb/client/WriteOptionsTest.java
- client/src/test/java/com/influxdb/client/internal/RetryAttemptTest.java
Related to #145
1. default value for `retryInterval` is 5_000
1. added exponential backoff strategy for batch writes
1. added `maxRetries` - the number of max retries when write fails - `3`
1. added `maxRetryDelay` -  the maximum delay between each retry attempt in milliseconds - `180_000`
1. added `exponentialBase` -  the base for the exponential retry delay, the next delay is computed as `retryInterval * exponentialBase^(attempts-1) + random(jitterInterval)` 
1. retry also network strategy
1. other http request doesn't have retry strategy
> feat: add exponential backoff strategy for retry

- client-kotlin/src/main/kotlin/com/influxdb/client/kotlin/InfluxDBClientKotlinFactory.kt
- client-reactive/src/main/java/com/influxdb/client/reactive/InfluxDBClientReactiveFactory.java
- client-scala/src/main/scala/com/influxdb/client/scala/InfluxDBClientScalaFactory.scala
- client/src/main/java/com/influxdb/client/InfluxDBClientFactory.java
- client/src/main/java/com/influxdb/client/InfluxDBClientOptions.java
- examples/README.md
- examples/pom.xml
- examples/src/main/java/example/WriteDataEverySecond.java
Closes #158
- improved documentation about `username/password` auth
- added `examples/README.md` as a start point to new examples
- added example how to write data every seconds to the InfluxDB.
> docs: improved documentation about username/password auth; added new write example

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/internal/AbstractWriteClient.java
- client/src/main/java/com/influxdb/client/write/events/WriteRetriableErrorEvent.java
- client/src/test/java/com/influxdb/client/ITQueryService.java
- client/src/test/java/com/influxdb/client/MockLogHandler.java
- client/src/test/java/com/influxdb/client/WriteApiTest.java
The message looks like:
_The retriable error occurred during writing of data. Reason: 'org 04014de4ed590000 has exceeded limited_write plan limit'. Retry in 5000ms._
> feat: improved logging message for retries

- CHANGELOG.md
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/LimitFlux.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/LimitFluxTest.java
Closes #160 
Offset param could be 0 - FluxDSL
> fix: Offset param could be 0 - FluxDSL

- CHANGELOG.md
- client-core/src/main/java/com/influxdb/query/internal/FluxCsvParser.java
- client-core/src/test/java/com/influxdb/query/internal/FluxCsvParserTest.java
Closes #162 
The response from InfluxDB server is encoded in UTF-8 => `InputStreamReader` should use UTF-8 as en encoding.
> fix: query response parser should use UTF-8 encoding

- CHANGELOG.md
- pom.xml
Downgrade gson version from 2.8.6 to 2.8.5 in order to support Java 8.
Related gson issue: https://github.com/google/gson/issues/1608
gson 2.8.7 should fix this once it is released
Closes #
> fix: downgrade gson to 2.8.5 to support Java 8

- CHANGELOG.md
- flux-dsl/src/main/java/com/influxdb/query/dsl/Flux.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/ToFlux.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/ToFluxTest.java
Closes #170
Add `to` function without `org`.
> Similarly org and orgID are mutually exclusive and only required when writing to a remote host. 
https://github.com/influxdata/flux/blob/master/docs/SPEC.md#to
> feat: added `to` function without `org` parameter

- CHANGELOG.md
- client-core/src/main/java/com/influxdb/query/internal/FluxCsvParser.java
- client-core/src/test/java/com/influxdb/query/internal/FluxCsvParserTest.java
Closes #171
According to specification of Flux, the error could be propagated after "success" table:
> When an error occurs after some results have already been sent to the client the error will be encoded as the next table and the rest of the results will be discarded. In such a case the HTTP status code cannot be changed and will remain as 200 OK. 
https://github.com/influxdata/flux/blob/master/docs/SPEC.md#errors
> fix: query error could be after "success" table

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/internal/WriteApiBlockingImpl.java
- client/src/test/java/com/influxdb/client/WriteApiBlockingTest.java
Closes #174 
Fixed unnecessary API call when writing collection of Points.
> fix: Blocking API batches Point by precision

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/internal/AuthenticateInterceptor.java
- client/src/main/java/com/influxdb/client/write/Point.java
- client/src/test/java/com/influxdb/client/ITTemplatesApi.java
- client/src/test/java/com/influxdb/client/QueryApiTest.java
- client/src/test/java/com/influxdb/client/internal/AuthenticateInterceptorTest.java
Closes #178 
Fixed concatenation of url - avoid double backslash
> fix: concatenation of url

- CHANGELOG.md
- client-core/src/main/java/com/influxdb/query/internal/FluxCsvParser.java
- client-core/src/test/java/com/influxdb/query/internal/FluxCsvParserTest.java
CSV parser is able to parse export from UI
> feat: CSV parser is able to parse export from UI

- CHANGELOG.md
- flux-dsl/README.md
- flux-dsl/src/main/java/com/influxdb/query/dsl/Flux.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/TailFlux.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/TailFluxTest.java
Closes #189
Added Tail function to `flux-dsl`.
> feat: added Tail function

- .gitignore
- CHANGELOG.md
- client-core/src/main/java/com/influxdb/internal/AbstractQueryApi.java
- client-core/src/main/java/com/influxdb/query/internal/FluxCsvParser.java
- client-scala/README.md
- client-scala/src/main/scala/com/influxdb/client/scala/InfluxDBClientScalaFactory.scala
- client-scala/src/main/scala/com/influxdb/client/scala/internal/InfluxDBClientScalaImpl.scala
- client-scala/src/main/scala/com/influxdb/client/scala/internal/QueryScalaApiImpl.scala
- client-scala/src/test/scala/com/influxdb/client/scala/ITQueryScalaApiQuery.scala
- pom.xml
Closes #198 
The `Backpressure` with previous implementation didn't works. The our API didn't supports a `QueueOfferResult` that is result of [offer()](https://doc.akka.io/api/akka/2.6/akka/stream/javadsl/SourceQueue.html#offer(elem:T):java.util.concurrent.CompletionStage[akka.stream.QueueOfferResult]) so the API wasn't be able to slowdown producing of results.
Instead of complicated implementation of `QueueOfferResult` ([see example](https://doc.akka.io/docs/akka/current/stream/operators/Source/queue.html#example-boundedsourcequeue-)) we just switch to `Source.unfoldResource`.
> fix: use Source.unfoldResource of source for Querying [scala]

- CHANGELOG.md
- client-kotlin/src/main/kotlin/com/influxdb/client/kotlin/internal/QueryKotlinApiImpl.kt
- client-reactive/src/main/java/com/influxdb/client/reactive/internal/QueryReactiveApiImpl.java
- client-scala/src/main/scala/com/influxdb/client/scala/internal/QueryScalaApiImpl.scala
- client/src/main/java/com/influxdb/client/internal/QueryApiImpl.java
👋 Hi folks, I try make a humble contribution to fix a gzip compression issue during a query.
- the `Accept-Encoding` header is not used for influx 2.0 server because it always send back CSV data (the server didn't care if you asked for JSON)
- this header blocks the `Accept-Encoding: gzip` header from the `BridgeInterceptor` ([quick look here 👀](https://github.com/square/okhttp/blob/a8b5b5ecb24fa20cfd3b39fd81e7ba96c970d969/okhttp/src/main/kotlin/okhttp3/internal/http/BridgeInterceptor.kt#L69))
> fix: :bug: replace accept-encoding application/json to null for all clients

- CHANGELOG.md
- client/src/generated/java/com/influxdb/client/domain/BucketRetentionRules.java
- client/src/generated/java/com/influxdb/client/domain/DateTimeLiteral.java
Allow setting shard-group durations for buckets via API
> chore: updated Swagger API to latest version

- CHANGELOG.md
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/restriction/Restrictions.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/restriction/RestrictionsTest.java
Closes #212
The FluxDSL supports empty logic operator. It is useful for something like:
```java
String classCode = search.getClassCode();
restriction = Restrictions.and(
Restrictions.tag("containerId").equal(search.getContainerId()),
classCode != null ? Restrictions.tag("classCode").equal(classCode) : Restrictions.or(),
Restrictions.measurement().equal("data")
);
```
> feat(flux-dsl): supports empty logic operator

- CHANGELOG.md
- flux-dsl/README.md
- flux-dsl/src/main/java/com/influxdb/query/dsl/Flux.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/LastFlux.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/LastFluxTest.java
- scripts/checkstyle.xml
Closes #215
Allow queries like:
```java
Flux flux = Flux
.from("telegraf")
.last("_time");
```
> feat(flux-dsl): allow to specify  name of `column` in `last` function

- CHANGELOG.md
- client-core/src/main/java/com/influxdb/query/internal/FluxResultMapper.java
- client-core/src/test/java/com/influxdb/query/internal/FluxResultMapperTest.java
- client/src/test/java/com/influxdb/client/internal/MeasurementMapperTest.java
Closes #217
Supports enum types in mapping into POJO.
> feat(query): supports enum types in mapping into POJO

- .circleci/config.yml
- CHANGELOG.md
- README.md
- karaf/README.md
- karaf/karaf-assembly/pom.xml
- karaf/karaf-features/pom.xml
- karaf/karaf-features/src/main/feature/feature.xml
- karaf/karaf-kar/pom.xml
- karaf/pom.xml
- pom.xml
Closes #219
Apache Karaf support (depends on #220 )
> feat: Apache Karaf support

- CHANGELOG.md
- client-kotlin/src/test/kotlin/com/influxdb/client/kotlin/InfluxDBClientKotlinFactoryTest.kt
- client-legacy/src/main/java/com/influxdb/client/flux/FluxConnectionOptions.java
- client-legacy/src/main/java/com/influxdb/client/flux/internal/FluxService.java
- client-legacy/src/test/java/com/influxdb/client/flux/FluxClientTest.java
- client-reactive/src/test/java/com/influxdb/client/reactive/InfluxDBClientReactiveFactoryTest.java
- client-scala/src/test/scala/com/influxdb/client/scala/InfluxDBClientScalaFactoryTest.scala
- client/src/main/java/com/influxdb/client/InfluxDBClientOptions.java
- client/src/test/java/com/influxdb/client/InfluxDBClientFactoryTest.java
- client/src/test/java/com/influxdb/client/InfluxDBClientOptionsTest.java
- client/src/test/java/com/influxdb/client/InfluxDBClientTest.java
- pom.xml
Closes #226
Supports URL specified like:
- http://localhost:64348/influxDB/
- http://localhost:64348/influxDB
- http://localhost:64348/
- http://localhost:64348
- http://localhost:64348?readTimeout=1000&writeTimeout=3000&connectTimeout=2000&logLevel=HEADERS
- http://localhost:64348/influx?readTimeout=1000&writeTimeout=3000&connectTimeout=2000&logLevel=HEADERS
Updated Kotlin due the compatibility with JDK 16:
- ![image](https://user-images.githubusercontent.com/455137/121856041-554b0b00-ccf4-11eb-9a5d-e9de921d7b98.png)
- https://youtrack.jetbrains.com/issue/KT-44624
- https://app.circleci.com/pipelines/github/influxdata/influxdb-client-java/1045/workflows/4237df2a-3849-4f0c-a97a-133854ab36fd/jobs/3179
> fix: connection URL with custom base path, update Kotlin to 1.5.10

- spring/src/main/resources/META-INF/spring.factories
Closes #247
Related to https://github.com/influxdata/influxdb-client-java/pull/231
Remove `Influx2MetricsExportAutoConfiguration` auto configuration candidates which was removed in `3.0.0`.
> fix: remove unsupported Influx2MetricsExportAutoConfiguration

- CHANGELOG.md
- client-legacy/src/main/java/com/influxdb/client/flux/FluxConnectionOptions.java
- client-legacy/src/test/java/com/influxdb/client/flux/FluxConnectionOptionsTest.java
- client/src/main/java/com/influxdb/client/InfluxDBClientOptions.java
- client/src/test/java/com/influxdb/client/InfluxDBClientOptionsTest.java
- spring/src/main/java/com/influxdb/spring/influx/InfluxDB2AutoConfiguration.java
- spring/src/test/java/com/influxdb/spring/influx/InfluxDB2AutoConfigurationTest.java
Closes #240
Related to https://github.com/influxdata/EAR/issues/2223
Set default http protocol to `HTTP 1.1`.
> fix: set default HTTP protocol to HTTP 1.1

- CHANGELOG.md
- spring/README.md
- spring/pom.xml
- spring/src/main/java/com/influxdb/spring/health/InfluxDB2HealthIndicatorAutoConfiguration.java
- spring/src/main/java/com/influxdb/spring/influx/InfluxDB2AutoConfiguration.java
- spring/src/main/java/com/influxdb/spring/influx/InfluxDB2Properties.java
- spring/src/test/java/com/influxdb/spring/health/InfluxDB2HealthIndicatorAutoConfigurationTest.java
- spring/src/test/java/com/influxdb/spring/influx/InfluxDB2AutoConfigurationTest.java
Closes #243
Closes #237
This PR adds support for auto-configure `InfluxDBClientReactive` for `SpringBoot` and also change configuration prefix from `spring.influx2` to `influx` according to [Spring Docs](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.developing-auto-configuration.custom-starter.configuration-keys):
> feat: add support for auto-configure of reactive API

- CHANGELOG.md
- spring/README.md
- spring/src/main/java/com/influxdb/spring/influx/AbstractInfluxDB2AutoConfiguration.java
- spring/src/main/java/com/influxdb/spring/influx/InfluxDB2AutoConfigurationReactive.java
- spring/src/main/resources/META-INF/spring.factories
- spring/src/test/java/com/influxdb/spring/influx/InfluxDB2AutoConfigurationReactiveTest.java
- spring/src/test/java/com/influxdb/spring/influx/InfluxDB2AutoConfigurationTest.java
Closes #250
The SpringBoot auto-configuration works even without `influxdb-client-reactive`.
> fix: Spring auto-configuration works even without `influxdb-client-reactive`

- CHANGELOG.md
- client/src/generated/java/com/influxdb/client/service/QueryService.java
Closes #253
Avoid to read entire query response into byte arrays - https://square.github.io/retrofit/2.x/retrofit/retrofit2/http/Streaming.html
> fix: read entire query response into bytes array

- CHANGELOG.md
- README.md
- client-kotlin/src/main/kotlin/com/influxdb/client/kotlin/InfluxDBClientKotlin.kt
- client-osgi/src/main/java/com/influxdb/client/osgi/LineProtocolWriter.java
- client-osgi/src/main/java/com/influxdb/client/osgi/PointWriter.java
- client-osgi/src/test/java/com/influxdb/client/osgi/LineProtocolWriterTest.java
- client-osgi/src/test/java/com/influxdb/client/osgi/PointWriterTest.java
- client-reactive/src/main/java/com/influxdb/client/reactive/InfluxDBClientReactive.java
- client-scala/src/main/scala/com/influxdb/client/scala/InfluxDBClientScala.scala
- client-scala/src/test/scala/com/influxdb/client/scala/ITQueryScalaApiQuery.scala
- client/README.md
- client/src/main/java/com/influxdb/client/InfluxDBClient.java
- client/src/main/java/com/influxdb/client/WriteApi.java
- client/src/main/java/com/influxdb/client/internal/InfluxDBClientImpl.java
- client/src/test/java/com/influxdb/client/ITWriteQueryApi.java
- client/src/test/java/com/influxdb/client/ITWriteTooManyData.java
- client/src/test/java/com/influxdb/client/InfluxDBClientTest.java
- client/src/test/java/com/influxdb/client/WriteApiTest.java
- examples/src/main/java/example/InfluxDB18Example.java
- examples/src/main/java/example/InfluxDB2Example.java
- examples/src/main/java/example/PlatformExample.java
- examples/src/main/java/example/WriteDataEverySecond.java
- examples/src/main/java/example/WriteDataPoint.java
- examples/src/main/java/example/WriteLineProtocol.java
- examples/src/main/java/example/WritePojo.java
Closes #167
1. Deprecated `com.influxdb.client.InfluxDBClient#getWriteApi()` to use `com.influxdb.client.InfluxDBClient#makeWriteApi()`
1. Use `WriteApiBlocking` in simple examples
1. Added warning if there is to much created `WriteApi` instances: 
> There is already created 10 instances of 'WriteApi'. The 'WriteApi' is suppose to run as a singleton and should be reused across threads.  Use 'WriteApiBlocking` if you would like to use one-time ingesting.
> docs: clarify how to use asynchronous non-blocking Write API

- CHANGELOG.md
- client/src/generated/java/com/influxdb/client/JSON.java
- client/src/generated/java/com/influxdb/client/domain/ArrayExpression.java
- client/src/generated/java/com/influxdb/client/domain/BinaryExpression.java
- client/src/generated/java/com/influxdb/client/domain/Block.java
- client/src/generated/java/com/influxdb/client/domain/CallExpression.java
- client/src/generated/java/com/influxdb/client/domain/ConditionalExpression.java
- client/src/generated/java/com/influxdb/client/domain/DictItem.java
- client/src/generated/java/com/influxdb/client/domain/ExpressionStatement.java
- client/src/generated/java/com/influxdb/client/domain/File.java
- client/src/generated/java/com/influxdb/client/domain/FunctionExpression.java
- client/src/generated/java/com/influxdb/client/domain/IndexExpression.java
- client/src/generated/java/com/influxdb/client/domain/LogicalExpression.java
- client/src/generated/java/com/influxdb/client/domain/MemberAssignment.java
- client/src/generated/java/com/influxdb/client/domain/MemberExpression.java
- client/src/generated/java/com/influxdb/client/domain/OptionStatement.java
- client/src/generated/java/com/influxdb/client/domain/ParenExpression.java
- client/src/generated/java/com/influxdb/client/domain/PipeExpression.java
- client/src/generated/java/com/influxdb/client/domain/Property.java
- client/src/generated/java/com/influxdb/client/domain/ReturnStatement.java
- client/src/generated/java/com/influxdb/client/domain/UnaryExpression.java
- client/src/generated/java/com/influxdb/client/domain/Variable.java
- client/src/generated/java/com/influxdb/client/domain/VariableAssignment.java
- client/src/generated/java/com/influxdb/client/domain/View.java
- client/src/test/java/com/influxdb/client/GeneratedCodeTest.java
- pom.xml
Closes #256
1. Avoid requirements to `jdk.unsupported` module. workaround: `--add-modules jdk.unsupported`
2. Update GSON to 2.8.8:
> fix: avoid requirements to jdk.unsupported module

- .circleci/config.yml
- CHANGELOG.md
Added JDK 17 (LTS) to CI pipeline instead of JDK 16.
> chore: use JDK 17 as the latest supported JDK

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/internal/AuthenticateInterceptor.java
- client/src/test/java/com/influxdb/client/ITInfluxDBClient.java
- client/src/test/java/com/influxdb/client/internal/AuthenticateInterceptorTest.java
The InfluxDB 2.1 OSS changed name of session cookie to `influxdb-oss-session`. As a solution this PR store all cookies from auth request.
https://github.com/influxdata/influxdb/pull/22632
> fix: session authentication for InfluxDB 2.1

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/internal/AbstractWriteClient.java
- client/src/test/java/com/influxdb/client/ITWriteQueryApi.java
Use asynchronous HTTP calls in batching writer to achieve better performance in a multithreading environment.
> chore: use async HTTP call in batching writer

- CHANGELOG.md
- client-core/src/main/java/com/influxdb/internal/AbstractRestClient.java
- client-reactive/README.md
- client-reactive/pom.xml
- client-reactive/src/main/java/com/influxdb/client/reactive/InfluxDBClientReactive.java
- client-reactive/src/main/java/com/influxdb/client/reactive/QueryReactiveApi.java
- client-reactive/src/main/java/com/influxdb/client/reactive/WriteOptionsReactive.java
- client-reactive/src/main/java/com/influxdb/client/reactive/WriteReactiveApi.java
- client-reactive/src/main/java/com/influxdb/client/reactive/internal/InfluxDBClientReactiveImpl.java
- client-reactive/src/main/java/com/influxdb/client/reactive/internal/QueryReactiveApiImpl.java
- client-reactive/src/main/java/com/influxdb/client/reactive/internal/WriteReactiveApiImpl.java
- client-reactive/src/test/java/com/influxdb/client/reactive/AbstractITInfluxDBClientTest.java
- client-reactive/src/test/java/com/influxdb/client/reactive/ITWriteQueryReactiveApi.java
- client-reactive/src/test/java/com/influxdb/client/reactive/WriteOptionsReactiveTest.java
- client-reactive/src/test/java/com/influxdb/client/reactive/WriteReactiveApiTest.java
- client-test/src/main/java/com/influxdb/test/AbstractMockServerTest.java
- client/src/main/java/com/influxdb/client/WriteApi.java
- client/src/main/java/com/influxdb/client/internal/AbstractInfluxDBClient.java
- client/src/main/java/com/influxdb/client/internal/AbstractWriteClient.java
- client/src/main/java/com/influxdb/client/internal/MeasurementMapper.java
- client/src/main/java/com/influxdb/client/internal/RetryAttempt.java
- client/src/main/java/com/influxdb/client/write/Point.java
- client/src/test/java/com/influxdb/client/WriteApiTest.java
- client/src/test/java/com/influxdb/client/internal/RetryAttemptTest.java
- examples/src/main/java/example/InfluxDB2ReactiveExample.java
- examples/src/main/java/example/InfluxDB2ReactiveExampleDSL.java
- examples/src/main/java/example/InfluxDB2ReactiveExamplePojo.java
- examples/src/main/java/example/InfluxDB2ReactiveExampleRaw.java
- examples/src/main/java/example/InfluxDB2ReactiveExampleWriteEveryTenSeconds.java
- pom.xml
Related to https://github.com/influxdata/EAR/issues/2287
Improvements of Reactive client:
> feat: write reactive client uses direct flow

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/write/Point.java
- client/src/test/java/com/influxdb/client/write/PointTest.java
Closes #282
Fixed serialization a Point into LineProtocol when tag's value is `null`.
> fix: serialization null tag's value into LineProtocol

- CHANGELOG.md
- client-kotlin/src/main/kotlin/com/influxdb/client/kotlin/internal/QueryKotlinApiImpl.kt
- client-scala/src/main/scala/com/influxdb/client/scala/internal/QueryScalaApiImpl.scala
- client/src/main/java/com/influxdb/client/internal/QueryApiImpl.java
- client/src/test/java/com/influxdb/client/QueryApiTest.java
Closes #284 
This PR fixes usage of default dialect in QueryAPI.
> fix: default dialect (#284)

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/internal/MeasurementMapper.java
- client/src/test/java/com/influxdb/client/internal/MeasurementMapperTest.java
Closes #293
Fixed mapping primitive floats into LineProtocol.
> fix: mapping measurement with primitive float

- CHANGELOG.md
- client-core/pom.xml
- client-reactive/pom.xml
- client/pom.xml
Closes #290
Fixed transient dependencies versions.
> fix: transient dependency of `okhttp`, `retrofit` and `rxjava`

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/internal/AbstractWriteClient.java
- client/src/test/java/com/influxdb/client/internal/PublishRuntimeErrorAsWriteErrorEventTest.java
Closes #291
Publishing runtime error as a WriteErrorEvent
> fix: publishing runtime error as a WriteErrorEvent

- CHANGELOG.md
- client/src/generated/java/com/influxdb/client/domain/PermissionResource.java
Added missing `PermissionResource` types.
> fix: add missing PermissionResources from Cloud API definition

- CHANGELOG.md
- client/pom.xml
- client/src/main/java/com/influxdb/client/internal/AbstractWriteClient.java
- client/src/main/java/com/influxdb/client/internal/InfluxDBClientImpl.java
Use native support for Rx request instead of callback emitter.
> fix: use native support for Rx request instead of callback emitter

- .circleci/config.yml
- CHANGELOG.md
The Codecov Bash Uploader is deprecated - https://docs.codecov.com/docs/about-the-codecov-bash-uploader. We have to switch to new one - https://docs.codecov.com/docs/codecov-uploader.
> chore(ci): use new Codecov uploader for reporting code coverage

- README.md
Closes #
Correct compile in README.md which doesn't exist anymore with Gradle 7.0 and was deprecated in favour of implementation since Gradle 5.0
- [✅] Rebased/mergeable
- [✅] A test has been added if appropriate
- [✅] `mvn test` completes successfully
- [✅] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [✅] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)
> fix: installation instruction for Gradle

- CHANGELOG.md
- client-core/src/main/java/com/influxdb/internal/AbstractQueryApi.java
- client-reactive/src/main/java/com/influxdb/client/reactive/internal/QueryReactiveApiImpl.java
- client-reactive/src/test/java/com/influxdb/client/reactive/QueryReactiveApiTest.java
Closes #311 
Do not deliver `throwable` if the consumer is already disposed or cancelled.
> fix(reactive): do not deliver exception when the consumer is disposed

- CHANGELOG.md
- flux-dsl/README.md
- flux-dsl/src/main/java/com/influxdb/query/dsl/Flux.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/FromFlux.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/JoinFlux.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/FluxTest.java
Closes #309 
Add support for timezones:
```java
Flux flux = Flux
.from("telegraf")
.withLocationFixed("-8h")
.count();
```
> feat(flux_dsl): add support for timezones

- CHANGELOG.md
- client-kotlin/src/main/kotlin/com/influxdb/client/kotlin/InfluxDBClientKotlinFactory.kt
- client-kotlin/src/test/kotlin/com/influxdb/client/kotlin/InfluxDBClientKotlinFactoryTest.kt
- client-reactive/src/main/java/com/influxdb/client/reactive/InfluxDBClientReactiveFactory.java
- client-reactive/src/test/java/com/influxdb/client/reactive/InfluxDBClientReactiveFactoryTest.java
- client-reactive/src/test/java/com/influxdb/client/reactive/QueryReactiveApiTest.java
- client-scala/src/main/scala/com/influxdb/client/scala/InfluxDBClientScalaFactory.scala
- client-scala/src/test/scala/com/influxdb/client/scala/InfluxDBClientScalaFactoryTest.scala
- client/src/main/java/com/influxdb/client/InfluxDBClientFactory.java
- client/src/main/java/com/influxdb/client/InfluxDBClientOptions.java
- client/src/test/java/com/influxdb/client/InfluxDBClientFactoryTest.java
- client/src/test/java/com/influxdb/client/InfluxDBClientOptionsTest.java
The url to connect to the InfluxDB is always evaluate as a connection string. The following code correctly set timeout:
```java
InfluxDBClient client = InfluxDBClientFactory.createV1("http://localhost:8086?writeTimeout=30000",
"my-username",
"my-password".toCharArray(),
"database",
"week");
```
---
Fixed flaky test: `doNotPropagateErrorOnCanceledConsumer()`.
> feat: url to connect to the InfluxDB is always evaluate as a connection string

- CHANGELOG.md
- flux-dsl/README.md
- flux-dsl/src/main/java/com/influxdb/query/dsl/Flux.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/ColumnsFlux.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/ColumnsFluxTest.java
Closes #336
Added support for [columns() function](https://docs.influxdata.com/flux/v0.x/stdlib/universe/columns/).
> feat: add support for `columns()` function

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/InfluxDBClientOptions.java
- client/src/test/java/com/influxdb/client/InfluxDBClientOptionsTest.java
Related to #335, https://github.com/influxdata/influxdb-client-java/issues/338#issuecomment-1103785269
Fix: If the `bucket` or the `org` is defined before `url` then the defaults for `bucket` and `org` is replaced with `null`.
> fix: evaluation of connection string

- client/pom.xml
- pom.xml
Related to #342
Related to #338
This PR explicitly exclude dependencies to `gson:2.8.x`. 
The Maven is not deterministic in resolving transient dependency. Maven chooses the first library it finds and it can be the older version (for more info see https://www.baeldung.com/maven-version-collision).
**Dependency report**
_**Before**_
```
...
[INFO] |  +- io.gsonfire:gson-fire:jar:1.8.5:compile
[INFO] |  |  \- (com.google.code.gson:gson:jar:2.8.6:compile - omitted for conflict with 2.9.0)
[INFO] |  +- com.squareup.retrofit2:converter-scalars:jar:2.9.0:compile
[INFO] |  |  \- (com.squareup.retrofit2:retrofit:jar:2.9.0:compile - omitted for duplicate)
[INFO] |  +- com.squareup.retrofit2:converter-gson:jar:2.9.0:compile
[INFO] |  |  +- (com.squareup.retrofit2:retrofit:jar:2.9.0:compile - …
```
> chore: explicit exclusion old one `gson` dependency

- CHANGELOG.md
- client-core/src/main/java/com/influxdb/query/internal/FluxCsvParser.java
- client/src/generated/java/com/influxdb/client/service/InvokableScriptsService.java
- client/src/main/java/com/influxdb/client/InfluxDBClient.java
- client/src/main/java/com/influxdb/client/InvokableScriptsApi.java
- client/src/main/java/com/influxdb/client/InvokableScriptsQuery.java
- client/src/main/java/com/influxdb/client/internal/InfluxDBClientImpl.java
- client/src/main/java/com/influxdb/client/internal/InvokableScriptsApiImpl.java
- client/src/test/java/com/influxdb/client/InvokableScriptsApiTest.java
- examples/README.md
- examples/src/main/java/example/InvokableScripts.java
Related to https://github.com/influxdata/openapi/pull/317
Renamed `InvocableScripts` to `InvokableScripts`.
> chore: rename InvocableScripts to InvokableScripts

- CHANGELOG.md
- spring/README.md
Related to https://github.com/influxdata/influxdb-client-java/issues/342
Add clarification how to deal with `OkHttp:4.9.3`  and Spring Boot.
> docs: clarify compatibility with Spring Boot

- client-reactive/README.md
- flux-dsl/README.md
Closes #340
1. Fixed `rxjava3` imports in READMEs.
2. Specified maven dependency in `flux-dsl`.
> docs: fix RxJava3 imports, specify Maven dependency for flux-dsl

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/internal/TasksApiImpl.java
- client/src/test/java/com/influxdb/client/ITTasksApi.java
Closes #351
Fixed creating `Task` with import statement:
```java
String flux = "import \"experimental\"\n"
+ "\n"
+ "from(bucket: \"my-bucket\")\n"
+ "    |> range(start: experimental.addDuration(d: -1d, to: today()), stop: today())\n"
+ "    |> max()";
Task task = tasksApi.createTaskCron("my-task", flux, "10 0 * * * *", organization.getId());
```
> fix: creating `Tasks` with `import` statements

- .github/PULL_REQUEST_TEMPLATE
- CHANGELOG.md
- client-scala/src/main/scala/com/influxdb/client/scala/InfluxDBClientScala.scala
- client-scala/src/main/scala/com/influxdb/client/scala/WriteScalaApi.scala
- client-scala/src/main/scala/com/influxdb/client/scala/internal/InfluxDBClientScalaImpl.scala
- client-scala/src/main/scala/com/influxdb/client/scala/internal/WriteScalaApiImpl.scala
- client-scala/src/test/scala/com/influxdb/client/scala/ITInfluxDBClientScala.scala
- client-scala/src/test/scala/com/influxdb/client/scala/ITQueryScalaApiQuery.scala
- client-scala/src/test/scala/com/influxdb/client/scala/InfluxDBClientScalaTest.scala
- client-scala/src/test/scala/com/influxdb/client/scala/InfluxDBUtils.scala
- client-scala/src/test/scala/com/influxdb/client/scala/WriteScalaApiTest.scala
- examples/README.md
- examples/src/main/java/example/ScalaQuery.scala
- examples/src/main/java/example/ScalaQueryDSL.scala
- examples/src/main/java/example/ScalaQueryRaw.scala
- examples/src/main/java/example/ScalaWriteApi.scala
Closes #125 
Added `WriteAPI` for Scala.
> feat(scala): Add WriteAPI for Scala

- CHANGELOG.md
- client-core/pom.xml
- client-kotlin/pom.xml
- client-legacy/pom.xml
- client-osgi/pom.xml
- client-reactive/pom.xml
- client-reactive/src/test/java/com/influxdb/client/reactive/QueryReactiveApiTest.java
- client-scala/cross/2.12/pom.xml
- client-scala/cross/2.13/pom.xml
- client-test/pom.xml
- client-utils/pom.xml
- client/pom.xml
- client/src/main/java/com/influxdb/client/internal/AbstractInfluxDBClient.java
- examples/pom.xml
- flux-dsl/pom.xml
- karaf/karaf-assembly/pom.xml
- karaf/karaf-features/pom.xml
- karaf/karaf-kar/pom.xml
- karaf/pom.xml
- pom.xml
- spring/pom.xml
This PR enables OkHttp retries strategy for connection failures. 
We don't need to disable the `retryOnConnectionFailure`. The retry logic in the OkHttp is not in a collision with our `exponential backoff strategy` for writes. OkHttp logic uses the possibility of routing to another "routes"  - e.g. network loopback or multiple proxies.
For more info see:
- https://github.com/square/okhttp/issues/5390
- https://github.com/ktorio/ktor/issues/1708#issuecomment-609988128
> fix: enable OkHttp retries for connection failure

- CHANGELOG.md
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/properties/FunctionsParameters.java
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/restriction/ColumnRestriction.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/restriction/RestrictionsTest.java
This PR fixes the escaping of double quotes in flux-dsl.
> fix: fixing double quote escape

- CHANGELOG.md
- client-kotlin/README.md
- client-reactive/README.md
- client-scala/README.md
- client/README.md
- client/src/main/java/com/influxdb/client/InfluxDBClientOptions.java
- client/src/main/java/com/influxdb/client/internal/AbstractInfluxDBClient.java
- client/src/test/java/com/influxdb/client/InfluxDBClientOptionsTest.java
- client/src/test/java/com/influxdb/client/InfluxDBClientTest.java
- client/src/test/resources/influx2.properties
Closes #370 
Added possibility to customise the `User-Agent` HTTP header:
```java
InfluxDBClientOptions options = InfluxDBClientOptions
.builder()
.url("http://localhost:8086")
.clientType("awesome-service")
.authenticateToken("my-token".toCharArray())
.build();
```
=>
```txt
User-Agent: influxdb-client-awesome-service/6.3.0
```
> feat: add possibility to customize the User-Agent HTTP header

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/internal/AbstractInfluxDBClient.java
- client/src/test/java/com/influxdb/client/InfluxDBClientTest.java
Redacted `Authorization` HTTP header from log.
> fix: redact the `Authorization` HTTP header from log

- CHANGELOG.md
- README.md
- client-core/src/main/java/com/influxdb/internal/AbstractQueryApi.java
- client-core/src/main/java/com/influxdb/query/InfluxQLQueryResult.java
- client/README.md
- client/src/generated/java/com/influxdb/client/service/InfluxQLQueryService.java
- client/src/main/java/com/influxdb/client/InfluxDBClient.java
- client/src/main/java/com/influxdb/client/InfluxQLQueryApi.java
- client/src/main/java/com/influxdb/client/domain/InfluxQLQuery.java
- client/src/main/java/com/influxdb/client/internal/InfluxDBClientImpl.java
- client/src/main/java/com/influxdb/client/internal/InfluxQLQueryApiImpl.java
- client/src/test/java/com/influxdb/client/ITInfluxQLQueryApi.java
- client/src/test/java/com/influxdb/client/internal/InfluxQLQueryApiImplTest.java
- examples/README.md
- examples/src/main/java/example/InfluxQLExample.java
Closes #365
Added an endpoint to query against the InfluxQL endpoint (v1)
> feat: expose `/query` endpoint to use InfluxQL (#365)

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/internal/TasksApiImpl.java
- client/src/test/java/com/influxdb/client/ITTasksApi.java
Related to https://github.com/influxdata/influxdb-client-python/issues/490
Append `task option` at the end of script. It allows create task with following Flux:
```
procTotal = from(bucket: "example-bucket")
|> range(start: -5m)
|> filter(fn: (r) => r._measurement == "processes" and r._field == "total")
procTotal
```
> fix: append `task option` at the end of script

- CHANGELOG.md
- client-core/src/main/java/com/influxdb/query/internal/FluxResultMapper.java
- client-core/src/test/java/com/influxdb/query/internal/FluxResultMapperTest.java
Closes #410
Fixed mapping aggregated results (changed type) from InfluxDB.
> fix: mapping `Number` types to POJO query output

- CHANGELOG.md
- client-scala/cross/2.13/pom.xml
Closes #433
Closes #435
1. Updated scala to `2.13.9`
2. Removed `scoverage-maven-plugin` because is no longer supported for Scala `2.13.9` - for more info see #433
> chore(deps): update scala to 2.13.9, remove scala coverage report plugin

- scripts/publish-site.sh
Simplify publishing GitHub pages by Docker to be platform independent.
This PR also change the **Deploy Maven site** from [**ReleaseCycleSettings.md**](https://github.com/bonitoo-io/influxdata/blob/main/influxdb-clients/ReleaseCycleSettings.md#3-deploy-maven-site) to:
```console
mvn site site:stage -DskipTests
docker run -it --rm \
-v "${PWD}":/code \
-v ~/.ssh:/root/.ssh \
-v ~/.gitconfig:/root/.gitconfig \
-w /code \
bitnami/git /code/scripts/publish-site.sh
```
> chore(docs): simplify publishing GitHub pages by Docker

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/AuthorizationsApi.java
- client/src/main/java/com/influxdb/client/internal/AuthorizationsApiImpl.java
- client/src/test/java/com/influxdb/client/ITAuthorizationsApi.java
Closes #453
This PR add possibility to use `AuthorizationPostRequest` and `AuthorizationUpdateRequest` in wrapped API - `AuthorizationApi`.
> feat(authorization): add possibility to use *Request object in wrapped API

- CHANGELOG.md
- client/src/generated/java/com/influxdb/client/service/InfluxQLQueryService.java
- client/src/test/java/com/influxdb/client/ITInfluxQLQueryApi.java
Switches to sending InfluxQL queries as a urlencoded form-body to ensure compatibility with 1.8.x's InfluxQL implementation.
See (#458)
> fix: Fix support for InfluxDB 1.8.x in InfluxQLQueryAPI

- .circleci/config.yml
- CHANGELOG.md
- pom.xml
This PR add new step to CircleCI build: `check-licenses`:
The `check-licenses` uses [license-maven-plugin](https://github.com/mathieucarbou/license-maven-plugin/blob/5cdc5cbc40f320f88e0891ba67db5727eefc3b3f/docs/index.md#dependency-enforcement) to verify that all dependencies has allowed licence: https://github.com/influxdata/influxdb-client-java/blob/a126aeb0521505349c65fa7c9bd720cdf943fdcc/pom.xml#L243
If there a dependency (`akka:2.7.0`) which has not allowed license then the build fail with following error:
> chore(ci): check dependency licenses

- CHANGELOG.md
- pom.xml
- spring/src/main/resources/META-INF/spring.factories
- spring/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Closes #468
Use `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports` for registration of auto-configuration.
Auto-configuration Registration
If you have created your own auto-configurations, you should move the registration from spring.factories 
under the org.springframework.boot.autoconfigure.EnableAutoConfiguration key to a new file named 
META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports. Rather than a single
comma-separate list, each line contains the fully qualified name of an auto-configuration class. 
See [the included auto-configurations](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConf …
> refactor(spring): move auto-configuration registration to `AutoConfiguration.imports` as is recommended from Spring Boot 2.7

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/internal/AbstractWriteBlockingClient.java
- client/src/main/java/com/influxdb/client/internal/AbstractWriteClient.java
Because the content-encoding was always getting set, we were never gzip encoding data. The content-encoding should only be set by the gzip class and only when we gzip data.
fixes: #521
> fix: do not hard-code content-encoding on writes

- CHANGELOG.md
- client-core/src/main/java/com/influxdb/query/InfluxQLQueryResult.java
- client/README.md
- client/src/main/java/com/influxdb/client/internal/InfluxQLQueryApiImpl.java
- client/src/test/java/com/influxdb/client/internal/InfluxQLQueryApiImplTest.java
> feat: add InfluxQL tags support

- .circleci/config.yml
- CHANGELOG.md
1. Fixed deploying artefacts to snapshot repository by CI:
1. Added JDK 20 to CI pipeline:
> fix: deploy by CI

- .circleci/config.yml
- CHANGELOG.md
- client-core/src/main/java/com/influxdb/query/internal/FluxCsvParser.java
- client-core/src/test/java/com/influxdb/query/internal/FluxCsvParserTest.java
Closes #644
When FluxCSVParser parses a value, and the stringValue is empty and the default value for the column is empty, now checks whether the data type for the column is "string" and if this is the case returns the empty default value instead of null.
Note that headerless csv tables will still return null and that null will be returned if the default value is null. 
Two tests are added to FluxCsvParserTest.
> fix: Issue/644

- .circleci/config.yml
- CHANGELOG.md
- client/src/main/java/com/influxdb/client/TasksApi.java
- client/src/main/java/com/influxdb/client/internal/TasksApiImpl.java
- client/src/test/java/com/influxdb/client/ITTasksApi.java
Closes #646 
adds findTasksStream
> feat: findTasksStream

- CHANGELOG.md
- client-core/src/main/java/com/influxdb/rest/ConnectionClosingInterceptor.java
- client-core/src/test/java/com/influxdb/rest/ITConnectionClosingInterceptor.java
This PR introduces the `ConnectionClosingInterceptor`. 
This interceptor closes connections that exceed a specified maximum lifetime age (TTL). It's beneficial for scenarios where your application requires establishing new connections to the same host after a predetermined  interval. This interceptor is most effective in applications that use a single connection, meaning requests  are not made in parallel.
```java
package example;
import java.time.Duration;
import java.util.Collections;
import okhttp3.OkHttpClient;
import okhttp3.Protocol;
import com.influxdb.client.InfluxDBClient;
import com.influxdb.client.InfluxDBClientFactory;
import com.influxdb.client.InfluxDBClientOptions;
import com.influxdb.rest.ConnectionClosingInterceptor;
public class InfluxTTLExample {
public static void …
```
> feat: add HTTP connection interceptor which TTL configuration

- spring/README.md
Closes #
1. When I introduced the influxdb-spring dependency into my Spring Boot 2.3 project, auto-configuration did not take effect, requiring additional code to be added. As a result, I updated the readme to provide instructions.
2. In the Maven repository influxdb-spring, the dependency for micrometer-registry-influx has already been added. Consequently, developers using influxdb-spring no longer need to manually import the micrometer-registry-influx dependency.  Due to package conflicts, the `spring-boot-actuator` may have relied on an earlier version of the `micrometer-core`. Therefore, it is necessary to specify a higher version here.
> docs: Add instructions for using Spring Boot prior to version 2.7

- .circleci/config.yml
- CHANGELOG.md
- README.md
- client-core/pom.xml
- client-kotlin/pom.xml
- client-reactive/src/main/java/com/influxdb/client/reactive/internal/QueryReactiveApiImpl.java
- client-scala/cross/2.13/pom.xml
- client/src/test/java/com/influxdb/client/WriteApiTest.java
- examples/pom.xml
- karaf/karaf-assembly/pom.xml
- karaf/karaf-features/pom.xml
- pom.xml
- spring/README.md
- spring/pom.xml
- spring/src/main/java/com/influxdb/spring/health/InfluxDB2HealthIndicatorAutoConfiguration.java
Closes #649
Migrate `influxdb-spring` from Spring Boot v2 to v3, Spring to v6.
> feat: upgrade Spring to v6, SpringBoot to v3

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/internal/InfluxQLQueryApiImpl.java
- client/src/test/java/com/influxdb/client/internal/InfluxQLQueryApiImplTest.java
Closes #684
Fixes logic in check of marker for end of table in CSV stream.  `InfluxQLQueryApiImpl:129`
> fix: Issue/684

- CHANGELOG.md
- flux-dsl/src/main/java/com/influxdb/query/dsl/functions/restriction/ColumnRestriction.java
- flux-dsl/src/test/java/com/influxdb/query/dsl/functions/restriction/RestrictionsTest.java
Closes #604 
can tested other repos because there are unwanted infrastructure dependency (why it needs to connect localhost:9999?)
in flux-dsl, if ColumnRestriction has custom() function and it is using regular expression operator(such as "=~"), then it does not use double quotes.
> fix: Issue/604

- CHANGELOG.md
- client-core/src/main/java/com/influxdb/exceptions/InfluxException.java
- client-core/src/test/java/com/influxdb/exceptions/InfluxExceptionTest.java
- client/src/main/java/com/influxdb/client/write/events/WriteErrorEvent.java
- client/src/test/java/com/influxdb/client/ITWriteApiBlocking.java
- client/src/test/java/com/influxdb/client/ITWriteQueryApi.java
- examples/README.md
- examples/src/main/java/example/WriteHttpExceptionHandled.java
Http Headers are already part of `InfluxException`.  In the `WriteApi` they can be accessed with an `EventListener`.  With `WriteApiBlocking` they get thrown in `write` method calls.
- print selected headers useful for debugging to error logs
- add an example of working with headers from `InfluxException`
Note that Cloud v3 and OSS v2 handle exceptional streamed or batched data on the server side a little bit differently.  It appears that with v3 cloud batches of data that include some invalid records along with valid ones, will still write the valid records and return a success HTTP status code.  OSS v2 on the other hand returns an error status triggering an exception.
> feat: better expose HTTP Error header information in error handling on write

- CHANGELOG.md
- client/src/main/java/com/influxdb/client/InfluxDBClientOptions.java
- client/src/main/java/com/influxdb/client/internal/AbstractInfluxDBClient.java
- client/src/main/java/com/influxdb/client/internal/InfluxDBClientImpl.java
- client/src/test/java/com/influxdb/client/InfluxDBClientTest.java
Closes [Issue](https://github.com/influxdata/influxdb-client-java/issues/645)
_ Prevent duplicate interceptors in the OkHttpBuilder
> feat: interceptor warning already signed out
